---
- hosts: localhost
  name: "Userspace playbook"
  gather_facts: no
  vars:
    user: "{{ lookup('env', 'USER') }}"
  tasks:
    - name: create src dir
      file: path=/home/{{ user }}/src state=directory

    - name: link dotfiles
      file:
        src: "{{ playbook_dir }}/.."
        dest: "/home/{{ user }}/src/env.dotfiles"
        state: link

    - name: yaourt all the things
      shell: make -C {{ playbook_dir }}/.. packages

    - name: stow dotfiles
      shell: stow -d /home/{{ user }}/src/env.dotfiles -t ~/ {{ item }}
      with_items: ['docker', 'git', 'gnupg', 'htop', 'idea', 'lang', 'mc', 'moc', 'shell', 'vim', 'wm']
