---
- hosts: localhost
  name: "Userspace playbook"
  gather_facts: no
  vars:
    user: "{{ lookup('env', 'USER') }}"
    dots: "/home/{{ user }}/src/env.dotfiles"
  tasks:
    - name: create src dir
      file: path=/home/{{ user }}/src state=directory

    - name: link dotfiles
      file:
        src: "{{ playbook_dir }}/.."
        dest: "{{ dots }}"
        state: link
      when: '"{{ playbook_dir }}" != "{{ dots }}/_ansible"'

    - shell: "hostname -s"
      register: shell_hostname

    - shell: "ls -lah {{ dots }}/_nodes/{{ shell_hostname.stdout }}"
      register: foo

    - name: stow nodefiles
      shell: stow -d {{ dots }}/_nodes -t ~/ {{ shell_hostname.stdout }}
      when: foo.rc == 0

    - name: stow dotfiles
      shell: stow -d {{ dots }} -t ~/ {{ item }}
      with_items:
        - devel
        - git
        - gnupg
        - htop
        - mc
        - moc
        - shell
        - vim
        - wm

    - name: stow bin
      shell: stow -d {{ dots }} -t ~/bin bin
