---
- hosts: localhost
  name: "Userspace playbook"
  gather_facts: no
  vars:
    user: "{{ lookup('env', 'USER') }}"
    dots: "/home/{{ user }}/src/env.dotfiles"
  tasks:
    - name: create src dir
      file: path=/home/{{ user }}/src state=directory

    - name: link dotfiles
      file:
        src: "{{ playbook_dir }}/.."
        dest: "{{ dots }}"
        state: link
      when: '"{{ playbook_dir }}" != "{{ dots }}/_ansible"'

    - name: yaourt all the things
      shell: make -C {{ playbook_dir }}/.. packages

    - name: stow dotfiles
      shell: stow -d {{ dots }} -t ~/ {{ item }}
      with_items: ['devel', 'git', 'gnupg', 'htop', 'mc', 'moc', 'net', 'shell', 'vim', 'wm']
